version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet:1-8.0
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=LocadoraVeiculosDB;User Id=sa;Password=SenhaForte@123;TrustServerCertificate=True

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SenhaForte@123
    ports:
      - "1433:1433"
